# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LofiPlayer < Formula
  desc "Keyboard-driven TUI for lofi, chillhop and ambient internet radio"
  homepage "https://github.com/iRootPro/lofi-player"
  version "0.1.6"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.6/lofi-player_0.1.6_darwin_amd64.tar.gz"
      sha256 "a5e62774d219e25fbad62721f8d71a6e4220a82fd84759714a59f374bcef8c8f"

      define_method(:install) do
        bin.install "lofi-player"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.6/lofi-player_0.1.6_darwin_arm64.tar.gz"
      sha256 "732543454358ec233a3e950378cd4b7bd2ca15176a70a623a0783371e6cf270a"

      define_method(:install) do
        bin.install "lofi-player"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.6/lofi-player_0.1.6_linux_amd64.tar.gz"
      sha256 "2155944a08d1aa1aa152ca00fdafb3675e9e09d5aca1dda701d178ec3eef74e2"
      define_method(:install) do
        bin.install "lofi-player"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.6/lofi-player_0.1.6_linux_arm64.tar.gz"
      sha256 "86c52af487f3096b34405331afd3bcbe4b195b4a19dd93d88896ebb1304fa1c7"
      define_method(:install) do
        bin.install "lofi-player"
      end
    end
  end

  test do
    system "#{bin}/lofi-player", "--version"
  end
end
