# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LofiPlayer < Formula
  desc "Keyboard-driven TUI for lofi, chillhop and ambient internet radio"
  homepage "https://github.com/iRootPro/lofi-player"
  version "0.1.8"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.8/lofi-player_0.1.8_darwin_amd64.tar.gz"
      sha256 "40f633b7730a4341fda0f8badbc8349d18dd647ed9af7655a9262e1356943d16"

      define_method(:install) do
        bin.install "lofi-player"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.8/lofi-player_0.1.8_darwin_arm64.tar.gz"
      sha256 "3238e50ae091b2a0319d72c2402bd424360816e46de1076f9cd85668a23c10d9"

      define_method(:install) do
        bin.install "lofi-player"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.8/lofi-player_0.1.8_linux_amd64.tar.gz"
      sha256 "895009edd13a1dc74db961d0344636ffe093c46dad6f2a7e669c5e3ae469ece3"
      define_method(:install) do
        bin.install "lofi-player"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/lofi-player/releases/download/v0.1.8/lofi-player_0.1.8_linux_arm64.tar.gz"
      sha256 "38f4d7385cca056c3ed16623266523fa3f1147e0ab51bfc6f69207c4d8da5e0a"
      define_method(:install) do
        bin.install "lofi-player"
      end
    end
  end

  test do
    system "#{bin}/lofi-player", "--version"
  end
end
