# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdr < Formula
  desc "Terminal RSS/Atom reader with vim navigation, full article rendering and smart folders"
  homepage "https://github.com/iRootPro/rdr"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iRootPro/rdr/releases/download/v0.11.1/rdr_darwin_amd64.tar.gz"
      sha256 "adbbc25b8b33a73bad73cddb22cb6866c8165140917ee2b3c6bb4468f4455253"

      define_method(:install) do
        bin.install "rdr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iRootPro/rdr/releases/download/v0.11.1/rdr_darwin_arm64.tar.gz"
      sha256 "85bcfd3717ad2765d39abaa431a5cd450862e088b4b22ada688b5c5001e64bb2"

      define_method(:install) do
        bin.install "rdr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/rdr/releases/download/v0.11.1/rdr_linux_amd64.tar.gz"
      sha256 "7d217868359699655e88688865673bdbc9476a4e2ae6da7652f4599ee59732c4"
      define_method(:install) do
        bin.install "rdr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/rdr/releases/download/v0.11.1/rdr_linux_arm64.tar.gz"
      sha256 "9ae93e0c2f7e4c2316137df31df28d9136ee3729060d6f6ce38aa379cd4ed298"
      define_method(:install) do
        bin.install "rdr"
      end
    end
  end
end
