# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdr < Formula
  desc "Terminal RSS/Atom reader with vim navigation, full article rendering and smart folders"
  homepage "https://github.com/iRootPro/rdr"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iRootPro/rdr/releases/download/v0.9.1/rdr_darwin_amd64.tar.gz"
      sha256 "181c230c6f8eb1f4cd8db9d01ce79ffde66bfac6574b57eacd599fe503f8e2da"

      define_method(:install) do
        bin.install "rdr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iRootPro/rdr/releases/download/v0.9.1/rdr_darwin_arm64.tar.gz"
      sha256 "e5076987728e656f563fa560baffc22499fe5cac8bfcd158c20a2fe8d9a2393a"

      define_method(:install) do
        bin.install "rdr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/rdr/releases/download/v0.9.1/rdr_linux_amd64.tar.gz"
      sha256 "e7e934ca7bbbdd9e478a175fca666927fbf798f48d50c25dc254d7c6b7796c56"
      define_method(:install) do
        bin.install "rdr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iRootPro/rdr/releases/download/v0.9.1/rdr_linux_arm64.tar.gz"
      sha256 "912dac6a3adf183a857abb39a8b7a955e02d13d99cd884ef923ad4b5f9d53f42"
      define_method(:install) do
        bin.install "rdr"
      end
    end
  end
end
